defaults:
    - agent: sac_pebble
    
# this needs to be specified manually
experiment: sdp_pretrain

# reward learning
segment: 50
activation: leaky_relu
init: default
prior_data_amount: 1000
num_seed_steps: 1000
num_unsup_steps: 5000
num_interact: 5000
reward_lr: 0.0003
reward_batch: 128
reward_update: 50
rm_train_batch_size: 128
feed_type: 0
reset_update: 100
topK: 5 
ensemble_size: 3
max_feedback: 1400
large_batch: 10
label_margin: 0.0
teacher_beta: -1
teacher_gamma: 1
teacher_eps_mistake: 0
teacher_eps_skip: 0
teacher_eps_equal: 0
std_white_noise: 0
round: 0
white_noise_label: 0
leverage_prior_data: 1
compute_canada: 1
num_included_unsup_steps: 0
include_unsup_steps: 1
# scheduling
reward_schedule: 0
sparse_reward: 0 
num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}
eval_data_type: random 
# evaluation config
eval_frequency: 5000
num_eval_episodes: 10
device: cpu
transfer_reward_model: 1
transfer_replay_buffer: 1
# logger
log_frequency: 3000
log_save_tb: true
prior_data_path: 0 
# video recorder
save_video: false

# setups
seed: 1

# Environment
env: dog_stand
gradient_update: 1
env_domain: METAWORLD

# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${env_domain}/${env}/REWARDLEARNING/H${diag_gaussian_actor.params.hidden_dim}_L${diag_gaussian_actor.params.hidden_depth}_lr${agent.params.actor_lr}/teacher_b${teacher_beta}_g${teacher_gamma}_m${teacher_eps_mistake}_s${teacher_eps_skip}_e${teacher_eps_equal}/label_smooth_${label_margin}/schedule_${reward_schedule}/${experiment}_init${num_seed_steps}_unsup${num_unsup_steps}_maxfeed${max_feedback}_agentupdate${transfer_replay_buffer}_pretrainreward_${transfer_reward_model}_num_inc_unsup_steps${num_included_unsup_steps}_incl_unsup_steps${include_unsup_steps}_act${activation}_seed${seed}