defaults:
    - agent: sac_pebble
    
# this needs to be specified manually
experiment: PEBBLE

# reward learning
segment: 50
activation: leaky_relu
num_seed_steps: 1000
num_unsup_steps: 5000
num_interact: 20000
reward_lr: 0.0003
reward_batch: 128
reward_update: 50
feed_type: 0
reset_update: 100
topK: 5
ensemble_size: 3
max_feedback: 1400
large_batch: 10
label_margin: 0.0
teacher_beta: -1
teacher_gamma: 1
teacher_eps_mistake: 0
teacher_eps_skip: 0
teacher_eps_equal: 0

# SURF
threshold_u: 0.99
lambda_u: 1
mu: 4
inv_label_ratio: 10
dataaug_window: 5
crop_range: 5

# scheduling
reward_schedule: 0

num_train_steps: 1e6
replay_buffer_capacity: ${num_train_steps}

# evaluation config
eval_frequency: 5000
num_eval_episodes: 10
device: cuda

# logger
log_frequency: 10000
log_save_tb: true
base_dir: temp
prior_data_path: 0
prior_data_amount: 59001
# video recorder
save_video: false

# setups
seed: 1

# Environment
env: dog_stand
gradient_update: 1

# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./sdp_surf/${env}/H${diag_gaussian_actor.params.hidden_dim}_L${diag_gaussian_actor.params.hidden_depth}_lr${agent.params.actor_lr}/teacher_b${teacher_beta}_g${teacher_gamma}_m${teacher_eps_mistake}_s${teacher_eps_skip}_e${teacher_eps_equal}/ratio_${inv_label_ratio}_threshold_${threshold_u}_lambda_${lambda_u}_mu_${mu}/schedule_${reward_schedule}/data_aug_w${dataaug_window}_c${crop_range}/${experiment}_init${num_seed_steps}_unsup${num_unsup_steps}_inter${num_interact}_maxfeed${max_feedback}_seg${segment}_act${activation}_Rlr${reward_lr}_Rbatch${reward_batch}_Rupdate${reward_update}_en${ensemble_size}_sample${feed_type}_large_batch${large_batch}_seed${seed}
